version: '3.8'

networks:
  rabbitmq-network:

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    hostname: '${RABBITMQ_HOSTNAME}'
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_MANAGEMENT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_MANAGEMENT_PASS}'
      RABBITMQ_DEFAULT_VHOST: '${RABBITMQ_MANAGEMENT_DEFAULT_VHOST}'
    ports:
      - '${RABBITMQ_HTTP_PORT:-5671}:5671'
      - '${RABBITMQ_HTTPS_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    volumes:
      - ./data:/var/lib/rabbitmq/
      - ./logs:/var/log/rabbitmq
      - ./rabbit.conf:/etc/rabbitmq/conf.d/10-defaults.conf
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rabbitmq-network
